# Site settings
title: "شَک - پادکست فلسفی نیچه"
description: "آیا تا به حال به تمام ارزش‌هایی که به ما آموخته‌اند، «شَک» کرده‌اید؟ سفری بی‌پروا به دل «فراسوی نیک و بد» نیچه"
baseurl: "" # Leave empty for user.github.io/repo-name or set to /repo-name
url: "" # Your GitHub Pages URL

# Podcast Info
host_name: "احسان"
about_intro: "اینجا پادکست «شَک» است؛ سفری بی‌پروا و قسمت به قسمت به دل یکی از خطرناک‌ترین کتاب‌های تاریخ فلسفه: «فراسوی نیک و بد» نیچه."
about_host: "من احسان هستم و قرار است با هم شجاعتِ عبور از مرزهای «نیک» و «بد» را تمرین کنیم. اینجا قرار نیست فیلسوف باشیم، فقط کافی‌ست شجاع و کنجکاو باشیم."
about_philosophy: "نیچه خطرناک است. نه به این خاطر که «بد» است، بلکه چون شما را وادار می‌کند که همه چیزهایی را که «خوب» می‌دانستید، زیر سؤال ببرید. این سفر برای کسانی است که آماده‌اند «دَم شیر را ببینند»."

# Build settings
markdown: kramdown
permalink: /episodes/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /episodes/:title/
  transcripts:
    output: false

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
